//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiro.Bibliotecas.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleFinanceiro.Bibliotecas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O arquivo de configuração &quot;{0}&quot; não está num formato XML válido..
        /// </summary>
        public static string Msg_ArquivoConfigXml_Invalido
        {
            get
            {
                return ResourceManager.GetString("Msg_ArquivoConfigXml_Invalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O arquivo de configuração &quot;{0}&quot; não pode ser carregado.d.
        /// </summary>
        public static string Msg_ArquivoConfigXml_NaoCarregado
        {
            get
            {
                return ResourceManager.GetString("Msg_ArquivoConfigXml_NaoCarregado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O arquivo de configuração &quot;{0}&quot; não foi encontrado..
        /// </summary>
        public static string Msg_ArquivoConfigXml_NaoEncontrado
        {
            get
            {
                return ResourceManager.GetString("Msg_ArquivoConfigXml_NaoEncontrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O arquivo de configuração &quot;{0}&quot; não contem as tags {1}..
        /// </summary>
        public static string Msg_ArquivoConfigXml_SemTag
        {
            get
            {
                return ResourceManager.GetString("Msg_ArquivoConfigXml_SemTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi possível autenticar seu acesso ao sistema. {0}.
        /// </summary>
        public static string Msg_AutenticacaoErro
        {
            get
            {
                return ResourceManager.GetString("Msg_AutenticacaoErro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A conexão com o banco de dados falhou. {0}.
        /// </summary>
        public static string Msg_ConexaoErro
        {
            get
            {
                return ResourceManager.GetString("Msg_ConexaoErro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Informação gravada com sucesso..
        /// </summary>
        public static string Msg_GravacaoSucesso
        {
            get
            {
                return ResourceManager.GetString("Msg_GravacaoSucesso", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na comunicação com o banco de dados. A operacao foi cancelada. {0}.
        /// </summary>
        public static string Msg_OperacaoErro
        {
            get
            {
                return ResourceManager.GetString("Msg_OperacaoErro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na execução do comando SQL. {0}.
        /// </summary>
        public static string Msg_SqlErro
        {
            get
            {
                return ResourceManager.GetString("Msg_SqlErro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuracao.xml.
        /// </summary>
        public static string XmlConfig_Arquivo_Nome
        {
            get
            {
                return ResourceManager.GetString("XmlConfig_Arquivo_Nome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string XmlConfig_Tag_ConnectionString
        {
            get
            {
                return ResourceManager.GetString("XmlConfig_Tag_ConnectionString", resourceCulture);
            }
        }
    }
}
