//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiro.BancoDeDados.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleFinanceiro.BancoDeDados.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O acesso ao arquivo do banco de dados &quot;{0}&quot; falhou..
        /// </summary>
        internal static string Msg_ConexaoErro_BancoErro {
            get {
                return ResourceManager.GetString("Msg_ConexaoErro_BancoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A autenticação falhou. Verifique o nome de usuário e a senha..
        /// </summary>
        internal static string Msg_ConexaoErro_LoginInvalido {
            get {
                return ResourceManager.GetString("Msg_ConexaoErro_LoginInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conexão de rede com o servidor &quot;{0}&quot; falhou..
        /// </summary>
        internal static string Msg_ConexaoErro_ServidorErro {
            get {
                return ResourceManager.GetString("Msg_ConexaoErro_ServidorErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebird.
        /// </summary>
        internal static string XmlConfig_Tag_ConnectionString_Firebird {
            get {
                return ResourceManager.GetString("XmlConfig_Tag_ConnectionString_Firebird", resourceCulture);
            }
        }
    }
}
